version: '3.8'

services:
  workspace:
    image: mcr.microsoft.com/devcontainers/python:1-3.11
    container_name: windx_workspace_dev
    volumes:
      - ..:/workspaces/Windx:cached
    working_dir: /workspaces/Windx
    command: sleep infinity
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    # Use a non-root vscode user when available
    user: vscode
